### ISSUE TITLE
Test throws error

### ISSUE THREAD

**Issue by ghost** [cnavarreteliz/datachile-api#5]
when I run test/_get.py, I get
`Traceback (most recent call last):
  File "_get.py", line 21, in <module>
    "parents": True
  File "...python3.6/site-packages/datachile/chilecube.py", line 110, in get
    q = agg.tidy
  File "...python3.6/site-packages/mondrian_rest/aggregation.py", line 94, in tidy
    measures = data['axes'][0]['members']
KeyError: 'axes`

**Comment by hlatorreg** [comment]
What if you print/debug the data object and watch the keys.

My guess is that it's 'axis' and not 'axes'.

**Comment by f3l1p3xlcc** [comment]
Hi, I have the following out:

Traceback (most recent call last):
  File "script1.py", line 6, in <module>
    "parents": True } ) 
  File ".../anaconda3/lib/python3.7/site-packages/datachile/chilecube.py", line 110, in get
    q = agg.tidy
  File "...anaconda3/lib/python3.7/site-packages/mondrian_rest/aggregation.py", line 116, in tidy
    'axes': data['axis_dimensions'][1:],
KeyError: 'axis_dimensions'
